### ISSUE TITLE
GPIO groups are not being properly set by install script

### ISSUE THREAD

**Issue by gavin660** [blakematis/UML290Modem-Verizon-Linux-scripts#8]
if you manually write to the gpio pin with
echo 1 > /sys/class/gpio/gpio13/value
you get  a permission denied error

it can be fixed by manually running
sudo usermod -a -G gpio ${USER}

needs to be investigated and fixed for install.sh to be functional

**Comment by blakematis** [comment]
Ok thanks for identifying that not sure but if that is why I had issues with the new template box I tried to install I will test it tonight

**Comment by gavin660** [comment]
found cause of bug:
install.sh is run as sudo, doing so runs commands as root
sudo usermod -a -G gpio ${USER} 
refers to root when script is run as sudo
if script is run without sudo it refers to current user IE enerdapt

echo_user.sh contains
    -------------
    |    !/bin/bash
    |    sudo echo ${USER} 
    -------------
input =
bash echo_user.sh
output = 
enerdapt

input =
sudo bash echo_user.sh
output = 
root
